import { User, Job, Application, Notification, ChatMessage, EarningsRecord } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-student-1',
    name: 'Student User',
    email: 'student@university.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verified: true,
    phone: '+91 98765 43210',
    bio: 'University student looking for flexible tutoring, design, and technical part-time jobs.',
    department: 'Computer Science',
    year: 'Semester 4',
    skills: ['Teaching', 'Mathematics', 'Science', 'Communication', 'Graphic Design', 'Data Entry'],
    gpa: 3.9,
    resumeUrl: 'student_resume.pdf',
    location: 'Calicut, Kerala',
    rating: 4.9,
    status: 'active',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-employer-1',
    name: 'Bright Academy',
    email: 'hiring@brightacademy.com',
    role: 'employer',
    avatar: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=300&auto=format&fit=crop&q=80',
    verified: true,
    companyName: 'Bright Academy',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    companyDescription: 'Premier education platform providing tutoring and academic support.',
    location: 'Calicut, Kerala',
    phone: '+91 98765 00001',
    rating: 4.9,
    status: 'active',
    createdAt: '2025-11-10T14:00:00Z',
  }
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-101',
    title: 'Online Tutor',
    companyId: 'user-employer-1',
    companyName: 'Bright Academy',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    department: 'Education & Science',
    location: 'Calicut, Kerala',
    workType: 'Part-Time',
    hourlyRate: 600,
    description: 'We are looking for a passionate tutor to teach school students (Classes 8–10) in Mathematics and Science subjects.',
    requirements: [
      'Good communication skills',
      'Strong knowledge in Math & Science',
      'Ability to explain concepts clearly',
      'Punctual and reliable',
    ],
    skillsRequired: ['Teaching', 'Mathematics', 'Science', 'Communication'],
    requiredEmployees: 3,
    selectedEmployees: 1,
    status: 'AVAILABLE',
    postedAt: '2026-08-10T10:00:00Z',
    deadline: '2026-09-01',
    featured: true,
    viewsCount: 310,
    applicationsCount: 12,
  },
  {
    id: 'job-102',
    title: 'Data Entry Operator',
    companyId: 'user-employer-1',
    companyName: 'InfoDesk',
    companyLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop&q=80',
    department: 'Administration',
    location: 'Calicut, Kerala',
    workType: 'Part-Time',
    hourlyRate: 500,
    description: 'Assist our operations team with fast and accurate MS Excel data processing and document tagging.',
    requirements: [
      'Proficiency in MS Excel & Typing',
      'Attention to detail',
      'Available 2 PM – 6 PM (Mon – Sat)',
    ],
    skillsRequired: ['MS Excel', 'Typing', 'Data Entry', 'Organization'],
    requiredEmployees: 2,
    selectedEmployees: 1,
    status: 'AVAILABLE',
    postedAt: '2026-08-12T14:30:00Z',
    deadline: '2026-08-28',
    featured: true,
    viewsCount: 280,
    applicationsCount: 9,
  },
  {
    id: 'job-103',
    title: 'Graphic Designer',
    companyId: 'user-employer-1',
    companyName: 'PixelMart',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    department: 'Design & Media',
    location: 'Calicut, Kerala',
    workType: 'Part-Time',
    hourlyRate: 700,
    description: 'Create eye-catching promotional banners, social media graphics, and digital brand assets.',
    requirements: [
      'Experience with Photoshop & Canva',
      'Creative portfolio',
      'Shift: 6 PM – 8 PM (Mon – Fri)',
    ],
    skillsRequired: ['Photoshop', 'Canva', 'Design', 'Creativity'],
    requiredEmployees: 2,
    selectedEmployees: 1,
    status: 'AVAILABLE',
    postedAt: '2026-08-14T09:00:00Z',
    deadline: '2026-08-30',
    featured: true,
    viewsCount: 420,
    applicationsCount: 15,
  },
  {
    id: 'job-104',
    title: 'Social Media Manager',
    companyId: 'user-employer-1',
    companyName: 'BrandUp',
    companyLogo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=200&auto=format&fit=crop&q=80',
    department: 'Marketing',
    location: 'Calicut, Kerala',
    workType: 'Flexible',
    hourlyRate: 800,
    description: 'Manage digital campaign posts, engage with audience comments, and track marketing growth metrics.',
    requirements: [
      'Strong social media copywriting',
      'Knowledge of content scheduling',
      'Shift: 5 PM – 9 PM (Mon – Fri)',
    ],
    skillsRequired: ['Social Media', 'Content', 'Marketing', 'Communication'],
    requiredEmployees: 3,
    selectedEmployees: 1,
    status: 'AVAILABLE',
    postedAt: '2026-08-15T16:20:00Z',
    deadline: '2026-09-05',
    featured: false,
    viewsCount: 195,
    applicationsCount: 8,
  },
  {
    id: 'job-105',
    title: 'Library Assistant',
    companyId: 'user-employer-1',
    companyName: 'Greenfield College',
    companyLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&auto=format&fit=crop&q=80',
    department: 'General Studies',
    location: 'Calicut, Kerala',
    workType: 'On-Campus',
    hourlyRate: 400,
    description: 'Assist students with book inventory checkouts, cataloging, and maintaining quiet study spaces.',
    requirements: [
      'Morning availability (9 AM – 1 PM)',
      'Organized and polite manner',
    ],
    skillsRequired: ['Organization', 'Communication', 'Customer Service'],
    requiredEmployees: 2,
    selectedEmployees: 0,
    status: 'AVAILABLE',
    postedAt: '2026-08-16T08:00:00Z',
    deadline: '2026-09-10',
    featured: false,
    viewsCount: 150,
    applicationsCount: 6,
  },
  {
    id: 'job-106',
    title: 'Campus Ambassador',
    companyId: 'user-employer-1',
    companyName: 'EduDrive',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    department: 'Events',
    location: 'Calicut, Kerala',
    workType: 'Flexible',
    hourlyRate: 700,
    description: 'Represent campus student initiatives, coordinate workshop registrations, and spread brand awareness.',
    requirements: [
      'Enthusiastic personality',
      'Weekend availability (Sat, Sun)',
    ],
    skillsRequired: ['Event Planning', 'Public Speaking', 'Communication'],
    requiredEmployees: 4,
    selectedEmployees: 1,
    status: 'AVAILABLE',
    postedAt: '2026-08-17T11:00:00Z',
    deadline: '2026-09-12',
    featured: true,
    viewsCount: 260,
    applicationsCount: 11,
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    jobId: 'job-101',
    studentId: 'user-student-1',
    studentName: 'Student User',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    studentEmail: 'student@university.edu',
    studentDepartment: 'Computer Science',
    jobTitle: 'Online Tutor',
    companyName: 'Bright Academy',
    status: 'PENDING',
    appliedAt: '20 May 2024',
    matchPercentage: 95,
    matchReasons: [
      'Matches Math & Science subject criteria',
      'Matches Computer Science department major',
      'Matches Mon, Wed, Fri schedule availability',
    ],
    coverLetter: 'I am passionate about teaching Math & Science to high school students and have prior tutoring experience.',
    availability: 'Mon, Wed, Fri (5 PM – 7 PM)',
  },
  {
    id: 'app-002',
    jobId: 'job-102',
    studentId: 'user-student-1',
    studentName: 'Student User',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    studentEmail: 'student@university.edu',
    studentDepartment: 'Computer Science',
    jobTitle: 'Data Entry Operator',
    companyName: 'InfoDesk',
    status: 'ACCEPTED',
    appliedAt: '18 May 2024',
    matchPercentage: 90,
    matchReasons: [
      'High proficiency in MS Excel & Data Processing',
      'Matches afternoon availability',
    ],
    coverLetter: 'Fast typing speed (65 WPM) and excellent attention to detail.',
    availability: 'Mon – Sat (2 PM – 6 PM)',
  },
  {
    id: 'app-003',
    jobId: 'job-103',
    studentId: 'user-student-1',
    studentName: 'Student User',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    studentEmail: 'student@university.edu',
    studentDepartment: 'Computer Science',
    jobTitle: 'Graphic Designer',
    companyName: 'PixelMart',
    status: 'REJECTED',
    appliedAt: '15 May 2024',
    matchPercentage: 92,
    matchReasons: ['Strong Photoshop & Canva skills'],
    coverLetter: 'Submitted sample design portfolio for review.',
    availability: 'Mon – Fri (6 PM – 8 PM)',
  },
  {
    id: 'app-004',
    jobId: 'job-105',
    studentId: 'user-student-1',
    studentName: 'Student User',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    studentEmail: 'student@university.edu',
    studentDepartment: 'Computer Science',
    jobTitle: 'Library Assistant',
    companyName: 'Greenfield College',
    status: 'ACCEPTED',
    appliedAt: '10 May 2024',
    matchPercentage: 85,
    matchReasons: ['Strong organization & campus communication'],
    coverLetter: 'Looking forward to supporting college library operations.',
    availability: 'Mon – Sat (9 AM – 1 PM)',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-student-1',
    title: 'Application Accepted! 🎉',
    message: 'InfoDesk accepted your application for Data Entry Operator.',
    type: 'application',
    read: false,
    createdAt: '2026-08-18T10:00:00Z',
    link: '/student/applications',
  },
];

export const MOCK_CHATS: ChatMessage[] = [];
export const MOCK_CHAT_MESSAGES: ChatMessage[] = [];

export const MOCK_EARNINGS: EarningsRecord[] = [
  {
    id: 'earn-001',
    studentId: 'user-student-1',
    jobTitle: 'Data Entry Shift',
    companyName: 'InfoDesk',
    hoursWorked: 5,
    hourlyRate: 500,
    totalAmount: 2500,
    status: 'PAID',
    date: '18 Aug 2026',
  },
  {
    id: 'earn-002',
    studentId: 'user-student-1',
    jobTitle: 'Library Support Shift',
    companyName: 'Greenfield College',
    hoursWorked: 4,
    hourlyRate: 437.5,
    totalAmount: 1750,
    status: 'PAID',
    date: '15 Aug 2026',
  },
];
